// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5msTrnOSU4dRY_MffXZYGDHf0R5Mtks',
    appId: '1:724127305294:web:195e82b9567cb6a5b8fd1f',
    messagingSenderId: '724127305294',
    projectId: 'fashions-store',
    authDomain: 'fashions-store.firebaseapp.com',
    storageBucket: 'fashions-store.appspot.com',
    measurementId: 'G-X4XB1FT80X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboatjeiz-_W5l_mqvb8H49y9OP_x7Dwo',
    appId: '1:724127305294:android:22afe2dccd3daf2bb8fd1f',
    messagingSenderId: '724127305294',
    projectId: 'fashions-store',
    storageBucket: 'fashions-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE4-6dNFRQMpCtkL5IFofO1AsXyaTocyY',
    appId: '1:724127305294:ios:293e987a81145228b8fd1f',
    messagingSenderId: '724127305294',
    projectId: 'fashions-store',
    storageBucket: 'fashions-store.appspot.com',
    iosBundleId: 'com.example.fashions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh5msTrnOSU4dRY_MffXZYGDHf0R5Mtks',
    appId: '1:724127305294:web:e02fb9ff0c59440ab8fd1f',
    messagingSenderId: '724127305294',
    projectId: 'fashions-store',
    authDomain: 'fashions-store.firebaseapp.com',
    storageBucket: 'fashions-store.appspot.com',
    measurementId: 'G-XQ1PTFGGX5',
  );
}
